#!/usr/bin/env python3
"""Turn the skill into a single paste-in prompt, and package it as a ZIP.

The skill is the source of truth. This generates dist/prompt.md from it so the
copy-paste version can never drift from the installed one. Run it after any edit
to SKILL.md, or let the GitHub Action run it on push.

This skill differs from a self-contained one in a way the prompt has to account
for: it reads a 303-episode transcript library that lives in a separate repo, and
it shells out to find_guest.py against a vendored index. Someone pasting a prompt
into a chat window has neither. Rather than pretend otherwise, the generated
prompt opens with a section telling the agent what it is missing and what to do
instead.
"""
import datetime
import pathlib
import re
import zipfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
NAME = "lenny-guest-product-mock-interview"
SKILL = ROOT / "skills" / NAME
OUT = ROOT / "dist" / "prompt.md"
ZIP = ROOT / "dist" / f"{NAME}.zip"

RAW = f"https://raw.githubusercontent.com/githrish/{NAME}/main/skills/{NAME}"
TRANSCRIPTS = "https://github.com/ChatPRD/lennys-podcast-transcripts"
TRANSCRIPTS_RAW = "https://raw.githubusercontent.com/ChatPRD/lennys-podcast-transcripts/main"

# Prepended to the skill body in the pasted version only. The installed skill has
# the index and the script on disk, so it needs none of this.
PASTE_MODE = f"""## Running this as a pasted prompt

You are reading this in a chat window, not from an installed skill folder. The
skill body below assumes two files are on disk that are not. Do not pretend to
use them.

**`scripts/find_guest.py` is not available.** Do not claim to run it. Match the
guest from the category lists near the end of this document, or ask the user to
name one.

**`references/episode-index.json` is not on disk.** It indexes all 303 episodes
with guest, title, date, keywords, YouTube link, and the `slug` used to build a
transcript URL. If you can browse the web, fetch it:

`{RAW}/references/episode-index.json`

Transcripts work exactly as described below. Fetch the one matched guest from:

`{TRANSCRIPTS_RAW}/episodes/<slug>/transcript.md`

If you cannot browse the web at all, say so in one line before the interview
starts, then run on the guest lists in this document alone. In that mode you must
not quote a guest or attribute a framework to them as though it came from their
episode. Where the feedback template calls for a direct quote, name the framework
and say the quote is unavailable in this mode.

To skip all of this, install the skill:

```bash
npx skills add githrish/{NAME} -g -y
```

---

"""


def strip_frontmatter(text):
    if text.startswith("---"):
        end = text.find("\n---", 3)
        if end != -1:
            return text[end + 4:].lstrip("\n")
    return text


def build_prompt():
    body = strip_frontmatter((SKILL / "SKILL.md").read_text(encoding="utf-8")).strip()
    # The skill's own H1 is replaced by the one this file writes.
    body = re.sub(r"\A# .*\n", "", body).strip()

    parts = [
        "# PM Mock Interviews with Lenny's Podcast Guests",
        "",
        f"> Generated from the skill at skills/{NAME}/.",
        "> Do not edit this file. Edit the skill and run scripts/build-prompt.py.",
        f"> Last generated {datetime.date.today().isoformat()}.",
        "",
        "Paste everything below into Claude, ChatGPT, Gemini, or any capable model.",
        "Attach your resume if you have one. Then say which company or guest you want.",
        "Nothing to clone. It fetches the one transcript it needs.",
        "",
        "Not affiliated with, endorsed by, or sponsored by Lenny's Podcast or Lenny",
        "Rachitsky. Transcripts are maintained separately by ChatPRD.",
        "",
        "---",
        "",
        PASTE_MODE.strip(),
        "",
        body,
        "",
    ]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    text = "\n".join(parts).rstrip() + "\n"
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(text):,} chars, {text.count(chr(10)) + 1:,} lines)")


def build_zip():
    """Package the skill folder for assistants that take a ZIP upload.

    Zips the skill directory itself, so the archive contains
    lenny-guest-product-mock-interview/SKILL.md and its references and scripts.
    Zipping the repo root instead is what drops those.
    """
    ZIP.parent.mkdir(parents=True, exist_ok=True)
    wanted = [p for p in sorted(SKILL.rglob("*")) if p.is_file() and p.suffix in {".md", ".json", ".py"}]
    # Fixed timestamps make the archive byte-identical for identical content.
    # Without this the zip differs on every build and, being binary, conflicts
    # whenever CI and a local build touch it at the same time.
    with zipfile.ZipFile(ZIP, "w", zipfile.ZIP_DEFLATED) as z:
        for f in wanted:
            rel = str(f.relative_to(SKILL.parent))
            info = zipfile.ZipInfo(rel, date_time=(1980, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = (0o755 if f.suffix == ".py" else 0o644) << 16
            z.writestr(info, f.read_bytes())

    names = zipfile.ZipFile(ZIP).namelist()
    assert any(n.endswith("SKILL.md") for n in names), "SKILL.md missing from archive"
    assert any(n.endswith("episode-index.json") for n in names), "episode index missing from archive"
    assert any(n.endswith("find_guest.py") for n in names), "find_guest.py missing from archive"
    print(f"wrote {ZIP.relative_to(ROOT)} ({len(names)} files)")


if __name__ == "__main__":
    build_prompt()
    build_zip()
